graphql:
  servlet:
    cors:
      allowed-origins:
      - ${env.PREVIEW}
      - ${env.PROD}

management:
  endpoints:
    web:
      cors:
        allowed-origins:
          - ${env.PREVIEW}
          - ${env.PROD}