spring:
  profiles:
    active: production
  application:
    name: Spring-Mailer-App
  mail:
    username: ${env.SMTP_USRNAME}
    password: ${env.SMTP_PASSWORD}
    host: ${env.SERVER_NAME}
    port: ${env.SERVER_PORT}
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

graphql:
  servlet:
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
    max-query-depth: 20
    websocket:
      enabled: false
    actuator-metrics: true

app.master: ${env.TO}
