spring:
  profiles:
    active: production
  application:
    name: Spring-Mailer-App
  mail:
    username: ${env.SMTP_USRNAME}
    password: ${env.SMTP_PASSWORD}
    host: ${env.SERVER_NAME}
    port: ${env.SERVER_PORT}
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
  thymeleaf:
    cache: false

graphql:
  servlet:
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
    max-query-depth: 2
    websocket:
      enabled: false
    actuator-metrics: true
    cors:
      allowed-origins:
      - ${env.PREVIEW}
      - ${env.PROD}
    cors-enabled: true

management:
  endpoints:
    web:
      cors:
        allowed-origins:
          - ${env.PREVIEW}
          - ${env.PROD}
        allowed-methods: GET

app:
  master: ${env.TO}
