spring:
  profiles:
    active: dev
  application:
    name: Spring-Mailer-App
  mail:
    username: ${env.SMTP_USRNAME}
    password: ${env.SMTP_PASSWORD}
    host: ${env.SERVER_NAME}
    port: ${env.SERVER_PORT}
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

graphql:
  servlet:
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
    max-query-depth: 20

app.master: ${env.TO}
